# Generated by Django 3.2.9 on 2021-11-29 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_blogs_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
